# Generated by Django 5.0.6 on 2024-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game_name',
            field=models.CharField(default='null_game', max_length=100),
            preserve_default=False,
        ),
    ]
